sudo: required
language: c
services:
- docker
env:
- IMG=fpco/pid1:lts-7.1
before_install:
- docker pull $IMG
script:
- docker run
    --rm
    --tty
    --volume $PWD:$PWD
    --workdir $PWD
    $IMG
    stack
        --allow-different-user
        --jobs $(cat /proc/cpuinfo|grep processor|wc -l)
        --no-terminal
      test
        --ghc-options '-optc-Os -optl-static -fPIC'
after_success:
- mkdir -p dist
- docker run
    --rm
    --tty
    --volume $PWD:$PWD
    --workdir $PWD
    $IMG
    bash -c 'upx -q --best --ultra-brute -o /sbin/pid1 $(stack path --local-install-root)/bin/pid1'
- if [ "$TRAVIS_TAG" != "" ]; then
    cp /sbin/pid1 ./dist/pid1-$TRAVIS_TAG-$TRAVIS_OS_NAME-amd64;
  else
    cp /sbin/pid1 ./dist/pid1-$TRAVIS_COMMIT-$TRAVIS_OS_NAME-amd64;
  fi
deploy:
  provider: s3
  access_key_id: AKIAIKYQAYTXLGDO4ZQA
  secret_access_key:
    secure: SZnqqCOVhNHZoljCUoSiHhnVo82r/vbt5Sy4GriuQbq4myposruC0cbQWEbDfwg3YIgU4EEteqll0syZDDYoeGDDQzO/C3hSLE3DmZ3Jga6FNK/9QQ+mLVKECboAr4Yn4WdCrAYPhKpzOIfYz6fetwPMDyzJZES5xXgcp6yEoOWy5+sQK/dZcVWmMEplKLRHpq23X5EiuYCmKbEbWxXltkF/krdiHRbUBqLfnXAcyy9CFwCo1MBPFNojreTw3BXB4pLyHNwDSJIRGxLZX254z2jgjXsShMRVXPg9jZQhxXeH8Ea2+quC6NFArHWmK4aE9ThoXMJ/Ogz7NuSFnbAJkhJgf0rGRnMspSuvZkoGASYPyBKNtOhg3l6l8yuSSmV89895cOQGXg9m/IO9wQDov079s5qezhL06icaeKeE4MGbHTh64LmPaUpbgVpmklJ+j3VFHt0xTta53Wf8egSwxAO0SZV7D4LyQNoh6KKkXNS9thzsnjrYx33lJHErq6O77B48k65s3xDHwfqiJNUBcXxQ+urrTbnwKlwF/d/qR2mgR6ymGi+aqbTqJX3ibfS0gP1Lxkmf4Rnc8oWwwEG5EzmU7/VERKfStOBUO/AK2PR9AYwK63vxZqZs/3unlPmCcDJ128rObvfDOrxhb0iD6Fm0BbkQ8l2wUiFJrmMaZjI=
  bucket: download.fpcomplete.com
  local_dir: dist
  upload-dir: pid1
  skip_cleanup: true
  acl: public_read
  on:
    all_branches: true
